blank_issues_enabled: false
contact_links:
  - name: Documentation – Storefront
    url: https://docs.dodopayments.com/features/storefront
    about: Review the official docs before filing an issue.

